### ISSUE TITLE
Explicit lucene version in org.eclipse.mylyn.tasks.index.core

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#389] opened 2024-01-31 07:15 UTC
Not sure why doing a Clean Up on Tasks made this one pop up

org.eclipse.mylyn.tasks.index.core is asking for lucene 9.5.0 (don't know why). What we get from p2 is 9.9.1

**Comment by ruspl-afed** [comment] 2024-01-31 07:19
> asking for lucene 9.5.0 (don't know why)

it is asking for it to not get older versions from platform, that was a case some time ago. If you think this is an issue, feel free to create a PR

**Comment by ruspl-afed** [comment] 2024-01-31 07:28
Interesting, perhaps there was a change of exported packages on lucene side or something similar.

> Changing the version in the manifest to 0.0.0 gets rid of the error.

Could you please create a PR with this very change to let us see what pipeline tests think about it?

**Comment by merks** [comment] 2024-01-31 07:30
The 9.5.0 is just a lower bound.  I built new version of lucene in the nightly build yesterday:

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/18e022db-64fb-4016-8f1b-40940d38ffd1)

I wonder which version is in your target platform?

It's strange that removing the bound would have any impact on the error.  Does that change which version is show in the plug-in's dependencies?

**Comment by gnl42** [comment] 2024-01-31 07:34
No, in either case its using 9.9.1

**Comment by ruspl-afed** [comment] 2024-01-31 07:38
> The 9.5.0 is just a lower bound.

Yes, true. It was an actual/ version of Apache Lucene when we (probably, I) did a reanimation procedures for Mylyn.

**Comment by merks** [comment] 2024-01-31 08:05
Very strange.  The problem you show is generally fixed by importing the package of the "indirectly required" class in the MANIFEST.MF...

**Comment by ruspl-afed** [comment] 2024-01-31 08:08
May it be the consequence of clean-up, that cleared some declarations, then imports, and finally changed the resolution chain on IDE side?

**Comment by merks** [comment] 2024-01-31 08:14
Maybe there is a split package involved because I see that org.apache.lucene.store is already imported.  Let me look...

**Comment by merks** [comment] 2024-01-31 08:17
This just makes no sense to me.  If I pull the latest, should I be able to reproduce this?

**Comment by gnl42** [comment] 2024-01-31 08:17
Clean up only affects the java classes. maven build has the same problem

**Comment by gnl42** [comment] 2024-01-31 08:23
@merks Yes. Just select the Tasks node, right click, and select Cleanup

**Comment by merks** [comment] 2024-01-31 08:40
I end up with a rather large set of errors:

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/109c53f2-e165-4cc5-8c0a-42c13f8e81cf)

This is generally how one fixes such a problem, i.e., import the package.

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/04ad9fa5-b544-46ec-acf9-9abffd02e5ce)

I really don't know how to make sense of all the errors and don't have significant time today to figure that out.

**Comment by gnl42** [comment] 2024-01-31 08:49
That works for me as well. But then we have 9.9.1 in place and 9.5.0 in another.

**Comment by merks** [comment] 2024-01-31 08:55
I only used that number because it's what PDE adds automatically.  You can set it to 9.5.0 instead if you like.  Also, given it's a test, it doesn't really matter to even set a constraint given that the constraint in the dependency will suffice.

**Comment by laeubi** [comment] 2024-01-31 09:01
Well the problem is more this one if I understand the screenshot correct:
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1842

only possible fix for now is update the BREE of all bundle < 9 to something > 9 .... but this has nothing to do with imports (directly).

**Comment by gnl42** [comment] 2024-01-31 09:08
Sorry, what is BREE?

I don't see anything in that ticket that relates to my problem

**Comment by merks** [comment] 2024-01-31 09:16
Searching for this "BREE" header, I see some inconsistencies that could explain some of the errors:

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/8a40220f-97cd-4066-9c78-afa89d076087)

**Comment by laeubi** [comment] 2024-01-31 09:18
The ones with `1.8` are most likely causing issues, the ones with `11` are just bogus if you depend on latest platform that requires java 17 (so your bundle will never run/resolve < 17).

**Closed** 2024-02-01 07:55 UTC
